blog_index:
    path: /
    defaults: {_controller: AppBundle:Blog:index}

blog_post:
    path: /posts/{slug}
    defaults: {_controller: AppBundle:Blog:postShow}

comment_new:
    path: /comment/{postSlug}
    defaults: {_controller: AppBundle:Blog:commentNew}

multipleSearch_page:
    path: /multiple_search
    defaults: {_controller: AppBundle:Blog:multipleSearchPage}

singleSearch_page:
    path: /single_search
    defaults: {_controller: AppBundle:Blog:singleSearchPage}
